### ISSUE TITLE
How predict half-life for a mRNA seq by using saluki

### ISSUE THREAD

**Issue by Jojo-LIU-LIU** [vagarwal87/saluki_paper#6]
Hi! I want to predict the half-lives of several human mRNAs by using saluki. However I just found some cases for 3'UTRs from MPRAs in this repo. I am wondering whether an example could be supplied? Or, an example to use saluki_predict_fasta.py in basenji repo? Thanks very much!

**Comment by vagarwal87** [comment]
Hi, The code that you allude to is almost what you need, with a few small adjustments for your use case: (https://github.com/vagarwal87/saluki_paper/blob/main/Fig6_S7/Siegel_testSet/fastUTR_predict.py).

you'll notice that it feeds in a 2D matrix of length 12,288 x 6. The first 4 rows are just the one hot encoding of the input sequence, which dna_io.dna_1hot(myseq) produces. The 5th row is zero throughout _except _ for the first position of each codon being encoded as 1. You can compute this directly from the open reading frame you provide. and then concatenate zeros for 5' UTRs and 3' UTRs.

The 6th row is an annotation of the positions of any 5' splice sites (0 throughout otherwise except for a 1 for each 5' splice site). For this, you'll need to map any splice sites from a GTF/BED file of exons from the genome onto the transcript you feed in from its 5' to 3' orientation. 

Then you can simply feed the prepared matrix in and perform a forward pass through the pretrained 50 models as shown in these examples (https://github.com/vagarwal87/saluki_paper/blob/main/Fig6_S7/runme.sh).

The saluki_predict_fasta.py performs all of these steps but assumes no splice sites, which was the case of these reporters. https://github.com/calico/basenji/blob/master/bin/saluki_bench_gtex.py and https://github.com/calico/basenji/blob/master/bin/saluki_ssd.py also gives some hints as to how to extract splice site info directly from a GTF file, if you needed.

We unfortunately don't have time to perform additional code development beyond these tools, but hopefully they are simple enough to modify to achieve your goal.

**Comment by Jojo-LIU-LIU** [comment]
Thank you very much, Vikram! I got it!
